version: "3"

services:
  
  app:
    build: ./nodejs
    volumes:
      - ./nodejs:/home/node/app
    ports:
      - "3001:3000"
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_banco
    volumes:
      - ./mysql_data:/var/lib/mysql